@echo off
echo Killing any process on port 8000...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8000" ^| find "LISTENING"') do taskkill /F /PID %%a
echo Starting backend server...
npm run server 