@echo off
echo Downloading CV template preview images...

if not exist "public\previews" mkdir "public\previews"

echo Downloading modern-professional.png...
curl -o "public\previews\modern-professional.png" "https://via.placeholder.com/300x400/3b82f6/ffffff?text=Modern+Professional"

echo Downloading corporate-executive.png...
curl -o "public\previews\corporate-executive.png" "https://via.placeholder.com/300x400/64748b/ffffff?text=Corporate+Executive"

echo Downloading finance-professional.png...
curl -o "public\previews\finance-professional.png" "https://via.placeholder.com/300x400/10b981/ffffff?text=Finance+Professional"

echo Downloading technical-engineer.png...
curl -o "public\previews\technical-engineer.png" "https://via.placeholder.com/300x400/8b5cf6/ffffff?text=Technical+Engineer"

echo Downloading software-developer.png...
curl -o "public\previews\software-developer.png" "https://via.placeholder.com/300x400/f43f5e/ffffff?text=Software+Developer"

echo Downloading data-scientist.png...
curl -o "public\previews\data-scientist.png" "https://via.placeholder.com/300x400/059669/ffffff?text=Data+Scientist"

echo Downloading creative-designer.png...
curl -o "public\previews\creative-designer.png" "https://via.placeholder.com/300x400/f59e0b/ffffff?text=Creative+Designer"

echo Downloading marketing-specialist.png...
curl -o "public\previews\marketing-specialist.png" "https://via.placeholder.com/300x400/6b7280/ffffff?text=Marketing+Specialist"

echo Downloading minimalist.png...
curl -o "public\previews\minimalist.png" "https://via.placeholder.com/300x400/374151/ffffff?text=Minimalist"

echo Downloading modern-executive.png...
curl -o "public\previews\modern-executive.png" "https://via.placeholder.com/300x400/1e40af/ffffff?text=Modern+Executive"

echo Downloading healthcare-professional.png...
curl -o "public\previews\healthcare-professional.png" "https://via.placeholder.com/300x400/047857/ffffff?text=Healthcare+Professional"

echo Downloading academic-researcher.png...
curl -o "public\previews\academic-researcher.png" "https://via.placeholder.com/300x400/be123c/ffffff?text=Academic+Researcher"

echo Downloading startup-founder.png...
curl -o "public\previews\startup-founder.png" "https://via.placeholder.com/300x400/d97706/ffffff?text=Startup+Founder"

echo Downloading consultant.png...
curl -o "public\previews\consultant.png" "https://via.placeholder.com/300x400/6d28d9/ffffff?text=Consultant"

echo Downloading project-manager.png...
curl -o "public\previews\project-manager.png" "https://via.placeholder.com/300x400/3b82f6/ffffff?text=Project+Manager"

echo Downloading sales-professional.png...
curl -o "public\previews\sales-professional.png" "https://via.placeholder.com/300x400/64748b/ffffff?text=Sales+Professional"

echo Downloading ux-designer.png...
curl -o "public\previews\ux-designer.png" "https://via.placeholder.com/300x400/059669/ffffff?text=UX+Designer"

echo Downloading product-manager.png...
curl -o "public\previews\product-manager.png" "https://via.placeholder.com/300x400/f59e0b/ffffff?text=Product+Manager"

echo Downloading operations-manager.png...
curl -o "public\previews\operations-manager.png" "https://via.placeholder.com/300x400/6b7280/ffffff?text=Operations+Manager"

echo Downloading senior-developer.png...
curl -o "public\previews\senior-developer.png" "https://via.placeholder.com/300x400/f43f5e/ffffff?text=Senior+Developer"

echo.
echo Download completed! Check public\previews directory for images.
pause 